---
    version: "3.4"
    
    services:
    ############################### Java App 1 ####################################
      app_1:
        build:
            context: ..
            dockerfile: Dockerfiles/Java-11/Dockerfile
        image: app-1
        container_name: app_1
        ports: 
          - 20001:20001
        environment:
          AWS_ACCESS_KEY_ID: anyKey
          AWS_SECRET_ACESS_KEY: anySecret
        volumes:
          - ${APP_1_PATH}:/app
          - ../local/.m2:/root/.m2
        tty: true